apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - sleep
    - infinity # Faz o container esperar para sempre
    resources: 
      limits: 
        memory: "128Mi"
        cpu: "0.5" 
      requests: 
        memory: "64Mi" 
        cpu: "0.3"
