apiVersion: v1
kind: Pod
metadata:
  name: giropops
  labels:
    name: giropops
spec:
  containers:
  - name: girus
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts: # list de volumes que serão montados no container
    - name: primeiro-emptydir # nome do volume
      mountPath: /giropops # diretório onde o volume será montado
  volumes: # lista de volumes
  - name: primeiro-emptydir # nome do volume
    emptyDir: # tipo de volume
      sizeLimit: 256Mi # tamanho máximo do volume